# Fixtures file hold the dependencies for spec helper

fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.3.2"
    apt:
      repo: "puppetlabs/apt"
      ref: "1.7.0"
    mysql:
      repo: "puppetlabs/mysql"
      ref: "2.3.1"
    wget:
      repo: "maestrodev/wget"
      ref: "1.5.6"      
    concat:
      repo: "puppetlabs/concat"
      ref: "1.1.2"
    python:
      repo: "stankevich/python"
      ref: "1.9.8"
      
  repositories:
    nfs: 
      repo: "https://github.com/haw-hh-ai-lab/puppet-module-nfs.git"
      branch: "fix_debian_service_cycle_squashed"

  symlinks:
    cloudstack: "#{source_dir}"