# Fixtures file hold the dependencies for spec helper

fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.6.0"
    nfs:
      repo: "echocat/nfs"
      ref: "1.8.1"      
    mysql:
      repo: "puppetlabs/mysql"
      ref: "2.3.1"
    apt:
      repo: "puppetlabs/apt"
      ref: "2.0.0"
    wget:
      repo: "maestrodev/wget"
      ref: "1.5.6"  
    concat:
      repo: "puppetlabs/concat"
      ref: "1.1.2" 
    python:
      repo: "stankevich/python"
      ref: "1.9.8"
    epel:
      repo: "stahnma/epel"
      ref: "1.2.2"

  symlinks:
    cloudstack: "#{source_dir}"