# Fixtures file hold the dependencies for spec helper?

fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.3.2"
    apt:
      repo: "puppetlabs/apt"
      ref: "1.7.0"
    mysql:
      repo: "puppetlabs/mysql"
      ref: "2.3.1"
    wget:
      repo: "maestrodev/wget"
      ref: "1.5.6"      
    nfs:
      repo: "haraldsk/nfs"    #TODO FROM GIT !!!
      ref: "1.1.1"
    concat:
      repo: "puppetlabs/concat"
      ref: "1.1.2"
      
  repositories:
    nfs: 
      repo: "https://github.com/haraldsk/puppet-module-nfs.git"
      branch: "v.2.0.x"

  symlinks:
    cloudstack: "#{source_dir}"