# Fixtures file hold the dependencies for spec helper?

fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.3.2"
    apt:
      repo: "puppetlabs/apt"
      ref: "1.7.0"
    mysql:
      repo: "puppetlabs/mysql"
      ref: "2.3.1"
    wget:
      repo: "maestrodev/wget"
      ref: "1.5.6"
      
#  repositories:
#    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    cloudstack: "#{source_dir}"