name    'lavaburn-cloudstack'
version '0.1.0'
source ''
author 'Nicolas Truyens'
license 'Apache License 2.0'
summary 'Puppet module for managing Apache Cloudstack'
description ''
project_page 'https://bitbucket.org/Lavaburn/lavaburn-cloudstack'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
dependency 'puppetlabs/stdlib', ''
dependency 'puppetlabs/apt', ''
dependency 'puppetlabs/mysql', ''
dependency 'maestrodev/wget', ''
